spring.application.name=8ThreadsEvent_Backend
cloudinary.cloud-name=dnpp54p32
cloudinary.api-key=685181829811545
cloudinary.api-secret=A26sIjUOVEjx1gpgPbzoJKC8axc

spring.datasource.url=jdbc:mariadb://localhost:3306/8threads_event_db
spring.datasource.username=root
spring.datasource.password=Tronganh123@
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

vnp.tmn.code=37KRXAMD
vnp.hash.secret=5VZV2LIHVR0AIWNW53YDYN3M4G1K287Q
vnp.url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnp.return.url=http://localhost:8080/api/v1/payment/vnpay-return

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=trongtan123tan@gmail.com
spring.mail.password=vqpmbydyzeqpdzki
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.ai.google.genai.api-key=AIzaSyAqzGeeOjStPm2l9nFCA1pxGd37o9pCug8
spring.ai.google.base-url=https://generativelanguage.googleapis.com
spring.ai.google.genai.chat.options.model=gemini-2.5-flash